# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ce2306d07ba02ea8b7f1b0609026f2fcc6aab0188638b0b112964fc6eaaa7fd74a35342e71aec5900290ad33ba53736693c30f0aa0a2c2f41c7613c4f724b5

test:
  secret_key_base: 2cb35a2c2677d72424e98489f5d6a200c1b6f029d31963c6afc1f4803572c9a08469a24de2052f34ffa0a6990460a513b7f8519d511827e981b39c1a737e3476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
